//
//  AVAnimatorView.m
//
//  Created by Moses DeJong on 3/18/09.
//
//  License terms defined in License.txt.

#import "AVAnimatorView.h"

#import <QuartzCore/QuartzCore.h>

#import "AVAnimatorMedia.h"

// private properties declaration for AVAnimatorLayer class
#import "AVAnimatorLayerPrivate.h"

// private method in Media class
#include "AVAnimatorMediaPrivate.h"

#import "AutoPropertyRelease.h"

// AVAnimatorLayer class

@implementation AVAnimatorLayer

// public properties

@synthesize layerObj = m_layerObj;
@synthesize mediaObj = m_mediaObj;
@synthesize imageObj = m_imageObj;

- (void) dealloc {
  // Detach but don't bother making a copy of the final image
  
  if (self.mediaObj) {
    [self.mediaObj detachFromRenderer:self copyFinalFrame:FALSE];
  }
  
  self.layer.contents = nil;
  
  [AutoPropertyRelease releaseProperties:self thisClass:AVAnimatorLayer.class];  
  [super dealloc];
}

// static ctor

+ (AVAnimatorLayer*) aVAnimatorLayer:(CALayer*)layer
{
  NSAssert(layer, @"layer");
  AVAnimatorLayer *obj = [[AVAnimatorLayer alloc] init];
  [obj autorelease];
  obj.layerObj = layer;
  return obj;  
}

- (id) init
{
  if ((self = [super init])) {
    // No specific defaults are needed
  }
  return self;
}

// Invoked with TRUE argument once renderer has been attached to loaded media,
// otherwise FALSE is passed to indicate the renderer could not be attached

- (void) mediaAttached:(BOOL)worked
{
  if (worked) {
    NSAssert(self.media, @"media is nil");
    NSAssert(self.media.frameDecoder, @"frameDecoder is nil");

    self->mediaDidLoad = TRUE;
  } else {
    self.mediaObj = nil;
    self->mediaDidLoad = FALSE;
  }
  
	return;
}

- (void) attachMedia:(AVAnimatorMedia*)inMedia
{
  if (self.mediaObj == inMedia) {
    // Detaching and the reattaching the same media is a no-op
    return;
  }
  
  if (inMedia == nil) {
    // Detach case, not attaching another media object so copy
    // the last rendered frame.
    
    [self.mediaObj detachFromRenderer:self copyFinalFrame:TRUE];
    self.mediaObj = nil;
    self.imageObj = nil;
    self->mediaDidLoad = FALSE;
    return;
  }
  
  [self.mediaObj detachFromRenderer:self copyFinalFrame:FALSE];
  self.mediaObj = inMedia;
  self.imageObj = nil;
  self->mediaDidLoad = FALSE;
  [self.mediaObj attachToRenderer:self];
}

// Implement read-only property for use outside this class

- (AVAnimatorMedia*) media
{
  return self->m_mediaObj;
}

- (CALayer*) layer
{
  return self->m_layerObj;
}

// This method is invoked as part of the AVAnimatorMediaRendererProtocol when
// a new frame image is generated by the media. Note that we only need to
// set the contents of the CALayer, rendering of the CGImageRef is handled
// by the CALayer class.

- (void) setImage:(UIImage*)image
{
  if (image == nil) {
    self.imageObj = nil;
    self.layer.contents = nil;
  } else {
    self.imageObj = image;
    CGImageRef cgImage = image.CGImage;
    self.layer.contents = (id) cgImage;
  }
}

- (UIImage*) image
{
  return self.imageObj;
}

@end
